[repository]
name = "intranet2-tremt"
managed_by_uv = false
changelog = "CHANGELOG.md"
version = "version.txt"
compose = "docker-compose.yml"

[repository.towncrier]
section = "Project"
settings = "towncrier.toml"

[backend]
path = "backend"

[backend.package]
name = "tremt.intranet2"
path = "backend"
changelog = "backend/CHANGELOG.md"
towncrier_settings = "backend/pyproject.toml"
base_package = "Products.CMFPlone"
publish = false

[frontend]
path = "frontend"

[frontend.package]
name = "volto-tremt-intranet2"
path = "frontend/packages/volto-tremt-intranet2"
changelog = "frontend/packages/volto-tremt-intranet2/CHANGELOG.md"
towncrier_settings = "frontend/packages/volto-tremt-intranet2/towncrier.toml"
base_package = "@plone/volto"
publish = false

[cookieplone]
template = "project"
template_version = "1d2012a950e4374f91c3f93e9531fde44b330ab3"
generated_date = "2025-09-23 17:51:05"
